sudo: required
language: node_js
node_js:
    - 7
services:
  - docker
cache:
  directories:
    - website/node_modules

script:
  - cd website
  - npm install
  - node build.js

deploy:
  - provider: script
    skip_cleanup: true
    script: sh gh-pages.sh output/ git@github.com:redbackup/redbackup.org.git master
    on:
      branch: master

